name: Main Build
on:
  push:
    branches: 
    - main
permissions: write-all
jobs:
  copypreview:
    name: Copy main branche to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        path: branchmain
    - name: git-publish-subdir
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: p18d
        FOLDER: branchmain
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
