name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
    - preview
permissions: write-all
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: Copy docs directory to branch directory in preview
    - uses: actions/checkout@v2
      with:
        ref: $(echo ${{ github.ref }} | sed "s/refs\/heads\///" )
      run: |
        echo "pwd"
        pwd
        echo "ls"
        ls
        echo "github.ref"
        echo ${{ github.ref }}
        branch=${{ github.ref }}
        branchname=$(echo "$branch" | sed "s/refs\/heads\///")
        echo "branchname"
        echo $branchname
        echo "github.workspace"
        echo ${{ github.workspace }}
      shell: bash
