name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
permissions: write-all
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: checkout p18d
      uses: actions/checkout@v2
      with:
        ref: p18d
    - name: copy p18d
      run: |
        mkdir -p p18d/docs
        cp -r docs p18d/docs/
        mkdir -p docs/preview/
        cp -r preview/docs docs/preview/
      shell: bash
    - name: checkout preview
      uses: actions/checkout@v2
      with:
        ref: preview
    - name: copy preview
      run: |
        cp -r docs preview
        mkdir -p docs/preview/docs
        cp -r preview docs/preview/docs/
      shell: bash
    - name: echo & ls
      run: |
        echo "cd docs"
        cd docs
        echo "*****"
        echo "ls"
        ls
        echo "***************"
        echo "cd docs/preview"
        cd preview
        echo "*****"
        echo "ls"
        ls
        echo "***************"
        echo "cd docs/preview/docs"
        cd docs
        echo "*****"
        echo "ls"
        ls
        echo "***************"
        echo "cd docs/preview/docs/preview"
        cd preview
        echo "*****"
        echo "ls"
        ls
      shell: bash
    - name: git-publish-subdir
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: p18d
        FOLDER: docs/preview
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
