name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
permissions: write-all
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: Copy docs directory to branch directory in preview
      run: |
        echo "pwd"
        pwd
        echo "ls"
        ls
        echo "github.ref"
        echo ${{ github.ref }}
        branch=${{ github.ref }}
        branchname=$(echo "$branch" | sed "s/refs\/heads\///")
        echo "branchname"
        echo $branchname
        echo "github.workspace"
        echo ${{ github.workspace }}
      shell: bash
    - name: Pushes to another repository folder
      uses: NoahDragon/action-push-repo-as-subdirectory-in-another-repo@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        dest-repo: "pmleonard/p18d.dev"
        dest-branch: 'preview'
        dest-folder: 'docs/preview'
