name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
  workflow_dispatch:
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@p18d
    - name: Copy docs directory to branch directory in preview
      run: cp "docs/*" "docs/preview/${GITHUB_REF##*/}"
