name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
permissions: write-all
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: preview
    - name: Copy docs directory to branch directory in preview
      run: |
        echo "pwd"
        pwd
        echo "ls"
        ls
        echo "github.ref"
        echo ${{ github.ref }}
        branch=${{ github.ref }}
        branchname=$(echo "$branch" | sed "s/refs\/heads\///")
        echo "branchname"
        echo $branchname
        echo "github.workspace"
        echo ${{ github.workspace }}
      shell: bash
    - name: copy
      run: |
        cp docs docs/preview/
    - name: git-publish-subdir
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: p18d
        FOLDER: docs/preview
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
