name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
    - preview
permissions: write-all
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: Copy docs directory to branch directory in preview
      run: |
        echo "pwd"
        pwd
        echo "ls"
        ls
        echo "github.ref"
        echo ${{ github.ref }}
        branch=${{ github.ref }}
        branchname=$(echo "$branch" | sed "s/refs\/heads\///")
        echo "branchname"
        echo $branchname
        echo "github.workspace"
        echo ${{ github.workspace }}
      shell: bash
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: docs
        dst_path: /docs/preview/
        dst_owner: pmleonard
        dst_repo_name: p18d.dev
        dst_branch: p18d
