name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
permissions: write-all
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: Copy docs directory to branch directory in preview
      run: |
        cp ${{ env.GITHUB_WORKSPACE }}/docs/ ${{ env.GITHUB_WORKSPACE }}/docs/preview/
    - name: git-publish-subdir
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: p18d
        FOLDER: docs/preview
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
