name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
permissions: write-all
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: Copy docs directory to branch directory in preview
      run: |
        cd ../
        cd ../
        cd ../
        cd ../
        echo "pwd"
        pwd
        echo "ls"
        ls
        echo "github.ref"
        echo ${{ github.ref }}
        echo "github.workspace"
        echo ${{ github.workspace }}
      shell: bash
