name: Preview Build
on:
  push:
    branches-ignore: 
    - main
    - release/*
    - p18d
permissions: write-all
jobs:
  copypreview:
    name: Copy preview branches to p18d branch subdirectory
    runs-on: ubuntu-latest
    steps:
    - name: checkout p18d
      uses: actions/checkout@v2
      with:
        ref: p18d
        path: branchp18d
    - name: copy p18d
      run: |
        mkdir -p temp/docs/preview
        cp -r -v branchp18d/* temp/
      shell: bash
    - name: checkout preview
      uses: actions/checkout@v2
      with:
        ref: preview
        path: branchpreview
    - name: copy preview
      run: |
        mkdir -p temp2/preview
        cp -r branchpreview/docs/* temp2/preview/
        cp -r temp2/preview temp/docs/
      shell: bash
    - name: echo & ls
      run: |
        echo "cd temp"
        cd temp
        echo "ls"
        echo "*****"
        ls
        echo "***************"
        echo "cd temp/docs"
        cd docs
        echo "ls"
        echo "*****"
        ls
        echo "***************"
        echo "cd temp/docs/preview"
        cd preview
        echo "ls"
        echo "*****"
        ls
      shell: bash
    - name: git-publish-subdir
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: p18d
        FOLDER: temp
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
